/**
 * Application config bootstrap (single owner).
 *
 * Creates ~/.chatgpt-mcp (or $CHATGPT_MCP_HOME), seeds repo `.env` and
 * user-scoped workers registry when absent, prints Cursor MCP JSON.
 *
 * Does not start Chrome/worker, write secrets, or overwrite existing config.
 *
 *   npm run setup
 *   CHATGPT_MCP_HOME=/tmp/foo npm run setup
 */
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  defaultWorkersFilePath,
  resolveUserPath,
} from "../config/load-config.js";

export interface SetupOptions {
  /** Override CHATGPT_MCP_HOME (absolute or ~/…). */
  home?: string;
  /** Override repository root (defaults to package root). */
  repoRoot?: string;
  /** Seed repo/.env. Source installer uses true; global CLI setup uses false. */
  projectEnv?: boolean;
}

export interface SetupReport {
  home: string;
  dbPath: string;
  logDir: string;
  /** Project runtime config at repo root when projectEnv=true. */
  envPath?: string;
  workersPath: string;
  distEntry: string;
  created: {
    env: boolean;
    workers: boolean;
    homeDirs: boolean;
  };
  warnings: string[];
  mcpJson: {
    mcpServers: Record<
      string,
      { command: string; args: string[]; env: Record<string, string> }
    >;
  };
}

function defaultRepoRoot(): string {
  return resolve(dirname(fileURLToPath(import.meta.url)), "../..");
}

/** First-run .env template (project runtime config at repo root). */
function buildEnvContents(opts: {
  home: string;
  dbPath: string;
  logDir: string;
  workersPath: string;
}): string {
  return [
    `# Generated by npm run setup — project runtime config (repo-scoped).`,
    `# User state (DB, logs, workers registry) lives under CHATGPT_MCP_HOME.`,
    `# Do not migrate this file into ~/.chatgpt-mcp without a deliberate design change.`,
    `CHATGPT_MCP_HOME=${opts.home}`,
    `HANDOFF_DB_PATH=${opts.dbPath}`,
    `LOG_DIR=${opts.logDir}`,
    `HANDOFF_HTTP_PORT=8787`,
    `CHATGPT_CDP_ENDPOINT=http://127.0.0.1:9222`,
    `CHATGPT_URL=https://chatgpt.com`,
    `HANDOFF_REMOTE_MCP_PORT=8790`,
    `HANDOFF_REMOTE_MCP_TOKEN=`,
    `# A1-S workers registry (user-scoped). Assign URLs via dashboard / gptmcp worker add.`,
    `HANDOFF_WORKERS_FILE=${opts.workersPath}`,
    `# Legacy single-worker fallback (optional; prefer HANDOFF_WORKERS_FILE):`,
    `# CHATGPT_WORKER_URL=https://chatgpt.com/c/REPLACE_WITH_WORKER_CHAT_ID`,
    ``,
  ].join("\n");
}

function seedWorkersTemplate(workersPath: string, repoRoot: string): boolean {
  if (existsSync(workersPath)) return false;
  mkdirSync(dirname(workersPath), { recursive: true });
  const example = join(repoRoot, "docs", "workers.example.a1s.json");
  if (existsSync(example)) {
    const raw = JSON.parse(readFileSync(example, "utf8")) as unknown;
    if (Array.isArray(raw) && raw.length > 0) {
      const first = raw[0] as Record<string, unknown>;
      writeFileSync(
        workersPath,
        `${JSON.stringify(
          [
            {
              id: "w1",
              workerUrl: String(
                first.workerUrl ?? "https://chatgpt.com/c/REPLACE_WORKER_1"
              ),
              cdpEndpoint: String(
                first.cdpEndpoint ?? "http://127.0.0.1:9222"
              ),
            },
          ],
          null,
          2
        )}\n`,
        "utf8"
      );
      return true;
    }
    copyFileSync(example, workersPath);
    return true;
  }
  writeFileSync(
    workersPath,
    `${JSON.stringify(
      [
        {
          id: "w1",
          workerUrl: "https://chatgpt.com/c/REPLACE_WORKER_1",
          cdpEndpoint: "http://127.0.0.1:9222",
        },
      ],
      null,
      2
    )}\n`,
    "utf8"
  );
  return true;
}

/**
 * Idempotent application bootstrap. Sync filesystem API — no half-async.
 * Never overwrites an existing `.env` or workers registry.
 */
export function runSetup(opts: SetupOptions = {}): SetupReport {
  const repoRoot = opts.repoRoot ?? defaultRepoRoot();
  const home = resolveUserPath(
    opts.home?.trim() ||
      process.env.CHATGPT_MCP_HOME?.trim() ||
      join(homedir(), ".chatgpt-mcp")
  );

  const dataDir = join(home, "data");
  const logDir = join(home, "logs");
  const dbPath = join(dataDir, "handoff.sqlite");
  const workersPath = defaultWorkersFilePath(home);
  const envPath = opts.projectEnv === false ? undefined : join(repoRoot, ".env");
  const distEntry = join(repoRoot, "dist", "index.js");
  const warnings: string[] = [];
  const created = { env: false, workers: false, homeDirs: false };

  if (!existsSync(dataDir) || !existsSync(logDir)) {
    created.homeDirs = true;
  }
  mkdirSync(dataDir, { recursive: true });
  mkdirSync(logDir, { recursive: true });

  // Project runtime config stays at repo/.env (intentional — not user-state).
  if (envPath && !existsSync(envPath)) {
    writeFileSync(
      envPath,
      buildEnvContents({ home, dbPath, logDir, workersPath }),
      "utf8"
    );
    created.env = true;
  }

  if (seedWorkersTemplate(workersPath, repoRoot)) {
    created.workers = true;
  }

  if (!existsSync(distEntry)) {
    warnings.push(
      "dist/index.js missing — run npm run build before gptmcp start"
    );
  }

  const mcpJson = {
    mcpServers: {
      "chatgpt-mcp": {
        command: "node",
        args: [distEntry, "mcp"],
        env: {
          CHATGPT_MCP_HOME: home,
          HANDOFF_DB_PATH: dbPath,
          LOG_DIR: logDir,
          HANDOFF_WORKERS_FILE: workersPath,
        },
      },
    },
  };

  return {
    home,
    dbPath,
    logDir,
    envPath,
    workersPath,
    distEntry,
    created,
    warnings,
    mcpJson,
  };
}

export function printSetupReport(report: SetupReport): void {
  console.log(`CHATGPT_MCP_HOME=${report.home}`);
  console.log(`HANDOFF_DB_PATH=${report.dbPath}`);
  console.log(`LOG_DIR=${report.logDir}`);
  console.log(`HANDOFF_WORKERS_FILE=${report.workersPath}`);
  console.log(
    `dist entry: ${report.distEntry}${existsSync(report.distEntry) ? "" : " (run npm run build)"}`
  );
  if (report.created.env && report.envPath) {
    console.log(`Wrote ${report.envPath} (project runtime config).`);
  }
  if (report.created.workers) {
    console.log(`Wrote ${report.workersPath} (seeded worker registry).`);
  }
  for (const w of report.warnings) {
    console.warn(`WARN: ${w}`);
  }
  console.log("");
  console.log("Paste into ~/.cursor/mcp.json (or merge under mcpServers):");
  console.log(JSON.stringify(report.mcpJson, null, 2));
  console.log("");
  console.log("Setup still required");
  console.log("  1. Paste MCP JSON → ~/.cursor/mcp.json → reload Cursor");
  console.log("  2. Connect ChatGPT (docs/connect-chatgpt.md)");
  console.log("  3. gptmcp start");
  console.log("  4. gptmcp open → Assign URL / New chat for worker w1");
  console.log("");
  console.log("Then");
  console.log("  gptmcp status          # exit 0 = healthy");
}

