#!/usr/bin/env npx tsx
/**
 * Create ~/.chatgpt-mcp (or $CHATGPT_MCP_HOME) and print Cursor MCP config.
 * Does not start Chrome/worker or write secrets.
 */
import { mkdirSync, existsSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(fileURLToPath(new URL("..", import.meta.url)));

function resolveUserPath(raw: string): string {
  const trimmed = raw.trim();
  if (trimmed === "~") return homedir();
  if (trimmed.startsWith("~/")) return resolve(join(homedir(), trimmed.slice(2)));
  return resolve(trimmed);
}

const home = resolveUserPath(
  process.env.CHATGPT_MCP_HOME?.trim() || join(homedir(), ".chatgpt-mcp")
);
const dataDir = join(home, "data");
const logDir = join(home, "logs");
const dbPath = join(dataDir, "handoff.sqlite");
const distEntry = join(repoRoot, "dist", "index.js");

mkdirSync(dataDir, { recursive: true });
mkdirSync(logDir, { recursive: true });

if (!existsSync(join(repoRoot, ".env")) && existsSync(join(repoRoot, ".env.example"))) {
  const example = [
    `# Generated by npm run setup — edit CHATGPT_WORKER_URL after first login`,
    `CHATGPT_MCP_HOME=${home}`,
    `HANDOFF_DB_PATH=${dbPath}`,
    `LOG_DIR=${logDir}`,
    `HANDOFF_HTTP_PORT=8787`,
    `CHATGPT_CDP_ENDPOINT=http://127.0.0.1:9222`,
    `CHATGPT_WORKER_URL=https://chatgpt.com/c/REPLACE_WITH_WORKER_CHAT_ID`,
    `CHATGPT_URL=https://chatgpt.com`,
    `HANDOFF_REMOTE_MCP_PORT=8790`,
    `HANDOFF_REMOTE_MCP_TOKEN=`,
    ``,
  ].join("\n");
  writeFileSync(join(repoRoot, ".env"), example);
  console.log(`Wrote ${join(repoRoot, ".env")} (edit CHATGPT_WORKER_URL).`);
}

const mcpBlock = {
  mcpServers: {
    "chatgpt-mcp": {
      command: "node",
      args: [distEntry, "mcp"],
      env: {
        CHATGPT_MCP_HOME: home,
        HANDOFF_DB_PATH: dbPath,
        LOG_DIR: logDir,
      },
    },
  },
};

console.log(`CHATGPT_MCP_HOME=${home}`);
console.log(`HANDOFF_DB_PATH=${dbPath}`);
console.log(`LOG_DIR=${logDir}`);
console.log(`dist entry: ${distEntry}${existsSync(distEntry) ? "" : " (run npm run build)"}`);
console.log("");
console.log("Paste into ~/.cursor/mcp.json (or merge under mcpServers):");
console.log(JSON.stringify(mcpBlock, null, 2));
console.log("");
console.log("Next:");
console.log("  1. npm run build");
console.log("  2. set CHATGPT_WORKER_URL in .env");
console.log("  3. npm run start          # CDP Chrome + remote-mcp + worker");
console.log("  4. Connect ChatGPT (docs/connect-chatgpt.md)");
console.log("  5. npm run check");
