import type { ParsedArgs } from "../args.js";
import { ExitCode } from "../exit-codes.js";
import { TOP_COMMANDS, WORKER_COMMANDS } from "../metadata.js";

function visibleTopCommands(): string[] {
  return TOP_COMMANDS.filter((c) => !c.hidden).map((c) => c.name);
}

function renderFish(): string {
  const top = visibleTopCommands().join(" ");
  const workers = WORKER_COMMANDS.filter((c) => !c.hidden).map((c) => c.name).join(" ");
  return `# generated by gptmcp completion fish\ncomplete -c gptmcp -f\ncomplete -c gptmcp -n '__fish_use_subcommand' -a '${top}'\ncomplete -c gptmcp -n '__fish_seen_subcommand_from worker' -a '${workers}'\n`;
}

function renderBash(): string {
  const top = visibleTopCommands().join(" ");
  const workers = WORKER_COMMANDS.filter((c) => !c.hidden).map((c) => c.name).join(" ");
  return `# generated by gptmcp completion bash\n_gptmcp_complete() {\n  local cur prev\n  COMPREPLY=()\n  cur="\${COMP_WORDS[COMP_CWORD]}"\n  prev="\${COMP_WORDS[COMP_CWORD-1]}"\n  if [[ "\${COMP_WORDS[1]}" == "worker" && \${COMP_CWORD} -eq 2 ]]; then\n    COMPREPLY=( $(compgen -W "${workers}" -- "$cur") )\n    return\n  fi\n  if [[ \${COMP_CWORD} -eq 1 ]]; then\n    COMPREPLY=( $(compgen -W "${top}" -- "$cur") )\n  fi\n}\ncomplete -F _gptmcp_complete gptmcp\n`;
}

export function runCompletion(args: ParsedArgs): number {
  const shell = args.positional[1];
  if (shell === "fish") {
    process.stdout.write(renderFish());
    return ExitCode.OK;
  }
  if (shell === "bash") {
    process.stdout.write(renderBash());
    return ExitCode.OK;
  }
  console.error("Usage: gptmcp completion <fish|bash>");
  return ExitCode.USAGE;
}
